# Compilation et test de projet .NET
# Plus d'info : https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configuration .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restauration des dépendances
      run: dotnet restore
    - name: Compilation
      run: dotnet build --no-restore
    - name: Exécution des tests
      env:
        InseeApiKey: ${{ secrets.INSEE_API_KEY }}
      run: dotnet test --no-build --verbosity normal
