# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
        DOTNET_SYSTEM_GLOBALIZATION_LOCALE: fr-FR

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        InseeApiKey: ${{ secrets.INSEE_API_KEY }}
      run: dotnet test --no-build --verbosity normal
